// Code generated by protoc-gen-go.
// source: cryptdo.proto
// DO NOT EDIT!

/*
Package cryptdopb is a generated protocol buffer package.

It is generated from these files:
	cryptdo.proto

It has these top-level messages:
	Message
*/
package cryptdopb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	// key derivation
	Iterations int32  `protobuf:"varint,1,opt,name=iterations" json:"iterations,omitempty"`
	Salt       []byte `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	// encryption
	Nonce      []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext []byte `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetIterations() int32 {
	if m != nil {
		return m.Iterations
	}
	return 0
}

func (m *Message) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *Message) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Message) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "cryptdo.Message")
}

func init() { proto.RegisterFile("cryptdo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2e, 0xaa, 0x2c,
	0x28, 0x49, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x8a, 0xb9,
	0xd8, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0xe4, 0xb8, 0xb8, 0x32, 0x4b, 0x52, 0x8b,
	0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x8a, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x90, 0x44, 0x84,
	0x84, 0xb8, 0x58, 0x8a, 0x13, 0x73, 0x4a, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0xc0, 0x6c,
	0x21, 0x11, 0x2e, 0xd6, 0xbc, 0xfc, 0xbc, 0xe4, 0x54, 0x09, 0x66, 0xb0, 0x20, 0x84, 0x03, 0x32,
	0x29, 0x39, 0xb3, 0x20, 0x23, 0xb5, 0xa8, 0x24, 0xb5, 0xa2, 0x44, 0x82, 0x05, 0x2c, 0x85, 0x24,
	0xe2, 0xc4, 0x1d, 0xc5, 0x09, 0xb5, 0xbf, 0x20, 0x29, 0x89, 0x0d, 0xec, 0x22, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x0e, 0xc6, 0x21, 0x5b, 0xa2, 0x00, 0x00, 0x00,
}
